baseURL: "https://compbiocore.github.io/"
languageCode: "en-us"
title: "Computational Biology Core Projects"

# Site params
params:
    description: "Here you can find documentation from workshops we conducted at Brown, as well as documentation for our software packages, tutorials, and best practices."

# Menu items
menu:
  main:
  - name: About
    weight: 1
    url: /about
  - name: Contact
    weight: 2
    url: /contact
