baseURL: "https://compbiocore.github.io/"
languageCode: "en-us"
title: "Computational Biology Core Projects"

# Site params
params:
    description: "Welcome to the Computational Biology CORE at Brown University’s software and workshop documentation page. Here you can find documentation on workshops we have conducted for the Brown community as well as documentation for software packages that we release."

# Menu items
menu:
  main:
  - name: About
    weight: 1
    url: /about
  - name: Contact
    weight: 2
    url: /contact
